import NavBar from "@/components/navbar/NavBar";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import { ThemeProvider } from "@/context/ThemeContext";
import AuthProvider from "@/components/navbar/AuthProvider";

export const metadata = {
  title: "Blogo",
  description: "Generated by Ayush Tiwari",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="dark dark:bg-[#111] bg-gray-500 text-white flex flex-col justify-between h-screen scroll-smooth transition-colors duration-200 ease-in">
        <AuthProvider>
          <ThemeProvider>
            <NavBar />
            {children}
            <Footer />
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
